### ISSUE TITLE
MAUI deprecates Xamarin.Forms

### ISSUE THREAD

**Issue by instantiator** [PoliceRewired/vpc-connect#2]
## Issue

This is both a bug and an enhancement ticket...

After a recent upgrade to Visual Studio, the project's mobile app tests have stopped running (although they _seem_ to compile). They previously ran successfully with 100% pass rate.

* Project references to the Android and iOS projects in **ConnectApp.AppTests** show warnings:
 ```
  incompatible target framework: MonoAndroid,version=v11.0
  incompatible target framework: Xamarin.iOS,version=v1.0
  ```
  <img width="1354" alt="Screenshot 2022-08-27 at 14 35 52" src="https://user-images.githubusercontent.com/1856578/187032821-99c565b4-2588-43e1-a421-ae155302c3bc.png">

* On run, the tests _seem_ to build but then fail, reporting:
  ```
  System.Exception : ApkFile or InstalledApp has not been configured.
  System.Exception : Must have either installed app or app bundle.
  ```

Cross-platform test project types are now missing from the templates available.

## Possible explanation

This is _believed_ to be because new MAUI support has eclipsed legacy Xamarin.Forms support.

## Possible solution

There are number of steps to migrate a project to MAUI:

* https://github.com/dotnet/maui/wiki/Migrating-from-Xamarin.Forms-(Preview)

Although it is not known if this will lead to a working test suite, it is worth doing - MAUI will be the supported framework going forwards.

## Chosen approach

I'll upgrade to MAUI.

I tried following the steps to migrate, but this is more complex than the usual project - I'd already made modifications to the Android and iOS projects to accommodate Firebase, and it wasn't porting easily. A more reliable approach is to start over, and port the UI and logic.

**Comment by instantiator** [comment]
A MAUI rebuild is underway, branch: [002-MAUI-rebuild](https://github.com/PoliceRewired/vpc-connect/tree/002-MAUI-rebuild)

- [x] Examine and attempt upgrade steps (abandoned)
- [x] Restructure for parallel projects - the old Xamarin.Forms build, and new MAUI build
- [x] Port existing pages, framework etc.
- [x] Upgrade to `AppShell` in preference to old `MasterDetailPage`
- [x] Upgrade to latest [Plugin.Firebase](https://github.com/TobiasBuchholz/Plugin.Firebase)
- [x] Upgrade and repair SQLite implementation
- [ ] ~~Add a new app tests suite~~

UI assessment and improvements are in a separate itemised list below.

App testing isn't currently supported in Visual Studio - this will become an additional item.

**Comment by instantiator** [comment]
SQLite packages proved difficult to get right for MAUI on iOS. It reliably threw this exception:

```
System.TypeInitializationException: The type initializer for 'SQLite.SQLiteConnection' threw an exception. ---> System.DllNotFoundException: e_sqlite3
  at at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
  at at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
  at at SQLitePCL.NativeLibrary.Load(String libraryName, Assembly assy, Int32 flags)
  at at SQLitePCL.Batteries_V2.MakeDynamic(String name, Int32 flags)
  at at SQLitePCL.Batteries_V2.DoDynamic_cdecl(String name, Int32 flags)
  at at SQLitePCL.Batteries_V2.Init()
  at at SQLite.SQLiteConnection..cctor()
```

I tried a lot of combinations. The solution came from this article: [Adding SQLite to the .NET MAUI application](https://vladislavantonyuk.azurewebsites.net/articles/Adding-SQLite-to-the-.NET-MAUI-application)
```xml
<PackageReference Include="sqlite-net-pcl" Version="1.8.116" />
<PackageReference Include="SQLitePCLRaw.core" Version="2.1.0" />
<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.0" />
<PackageReference Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="2.1.0" />
<PackageReference Include="SQLitePCLRaw.provider.sqlite3" Version="2.1.0" />
```

Although the versions are expected to change, this combination of packages seems to result in the right libraries being available to the app on both Android and iOS.

**Comment by instantiator** [comment]
Switching to [AppShell](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/create) is a good solution, and the old MasterDetailPage from Xamarin.Forms is now deprecated.

**Comment by instantiator** [comment]
Home page, emulator screenshots - side-by-side comparison...

| Android | iOS |
|-|-|
| <img width="504" alt="Screenshot 2022-10-08 at 15 05 13" src="https://user-images.githubusercontent.com/1856578/194711548-fe3adc1b-97f3-4ae7-a476-ae30cdf766b1.png"> | <img width="589" alt="Screenshot 2022-10-08 at 15 03 22" src="https://user-images.githubusercontent.com/1856578/194711555-297b6564-cbff-45df-b9f3-d196bc8f79a7.png"> |

There's still a little work to do.

- [x] Tweak header image to appear the right size on iOS
- [x] Tweak frames to properly wrap their contents on both (all pages)
- [x] Choose a better icon for messages / switch to all new
- [x] Ensure notification swipe is working, ensure archive option is working
- [x] Add a header to the shell menu
- [x] Display app version prominently on the support page
- [x] Limit debug buttons on the support page
- [x] Icons on both
- [x] Splash screens on both

**Comment by instantiator** [comment]
## Final tests
Release 2.0 (build 20)

| Test | iOS Debug | iOS Release | Android Debug | Android Release | Android Release (physical)
|-|-|-|-|-|-|
| Icon correct | ✅ | ✅ | 🆗 | 🆗 | 🆗 |
| App launches | ✅ | ✅ | ✅ | ✅ | ❌ |
| Splash screen correct | ✅ | ✅ | 🆗 | 🆗 | 🆗 |
| App gets push token | ✅ | ✅ | ✅ | ✅ | ✅ |
| User can register | ✅ | ✅ | ✅ | ✅ | ✅ |

## Android update

* Release 2.0 (build 21) replaces build 20 to address a crash immediately after splash screen
* Tested through a Play Store internal testing release, and then promoted to production

| Test | iOS Debug | iOS Release | Android Debug | Android Release | Android Release (physical)
|-|-|-|-|-|-|
| App launches | | | | ✅ | ✅ |

Known issues:

* Icon image is far larger than the icon, and cropped to the icon size by Android
* Splash screen is slightly wider than the page
